concurrency:
  group: deploy
  cancel-in-progress: false

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/Makefile"

permissions: read-all

jobs:
  build-ecr-image:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      DEPLOYMENT_ENV: dev
      ACCOUNT_ID: {ACCOUNT_ID}

  deploy-dev:
    needs: build-ecr-image
    uses: ./.github/workflows/terraform-deploy.yml@main
    secrets: inherit
    with:
      DEPLOYMENT_ENV: dev
      WORKING_DIRECTORY: infra
      EXTRA_TF_ARGS: '-var="ecr_image_tag=${{ github.sha }}"'

  e2e-tests:
    name: End 2 end tests
    needs: deploy-dev
    uses: ./.github/workflows/e2e-tests.yml
    secrets: inherit

  copy-ecr-image:
    needs: e2e-tests
    uses: ./.github/workflows/copy-image.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: sandbox
            account_id: {SANDBOX_ACCOUNT_ID}
          - env: prod
            account_id: {PROD_ACCOUNT_ID}
    with:
      DEPLOYMENT_ENV: ${{ matrix.env }}
      TARGET_IAM_ROLE: {TARGET_IAM_ROLE}
      TARGET_ACCOUNT_ID: ${{ matrix.account_id }}

  deploy-sandbox:
    needs: copy-ecr-image
    uses: ./.github/workflows/terraform-deploy.yml@main
    secrets: inherit
    with:
      DEPLOYMENT_ENV: sandbox
      WORKING_DIRECTORY: infra
      EXTRA_TF_ARGS: '-var="ecr_image_tag=${{ github.sha }}"'

  deploy-prod:
    needs: deploy-sandbox
    uses: ./.github/workflows/terraform-deploy.yml@main
    secrets: inherit
    with:
      DEPLOYMENT_ENV: prod
      WORKING_DIRECTORY: infra
      EXTRA_TF_ARGS: '-var="ecr_image_tag=${{ github.sha }}"'
