concurrency:
  group: validate
  cancel-in-progress: false

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "**/Makefile"

jobs:
  static-tests:
    name: Static tests
    uses: ./.github/workflows/lint-and-test.yml
    with:
      WORKING_DIRECTORY: infra

  infrastructure-validate:
    name: Validate Infrastructure
    uses: ./.github/workflows/terraform-validate.yml
    secrets: inherit
    with:
      WORKING_DIRECTORY: infra
      EXTRA_TF_ARGS: '-var="ecr_image_tag=${{ github.sha }}"'